- name: show return value of command module
  hosts: vagrant
  vars:
    foo: bar
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="{{ foo }} loging as user {{ login.stdout }}"
